language: go
sudo: required
go:
  - 1.9
services:
  - docker
install: true
script: make travis
deploy:
  provider: releases
  api_key:
    secure: CdygcKAdR+b/7mgkpJMtlBtOxirjL+bL4P4yHMoCPcf2Cf34VATJ+4iQX3a9gHoJI3LYMHvvJ7Khv6Cr7LHXARN1vxd360yKe2Gf+CbibXuljk7lNGgM0OmAa8OWLiDYJugGZIi+Nh+mGlvoM+T919twGMlP1nEO9I4Ac57PaPdEraVhsgkWZ3AejwDfGTbpWk2egGRFDo/aLd5M+j0XydeFshU22Eqn8MRjYoEibtS+tfbpv20t8L/loVLUNuFk7vpy+q7lJh6/UfEFeCmoNR077LWepDXXwR2zzfPaPpornRb7vaSP4yLygwgxVnmR43WRePvx+w96r+cPblZgxyEzR1wDOWG8yDA9ZtPE9RA09ZTlyN77DqkFLzCwrl0r7K0Ou6LIz4BPfkJ6DtG3h578o/00UGqmXeoNaRr5U6VChIbBAPQRZkf0HC+JNiMPFQ3QlmzUWm1+xTP7MLKUC6kwScKISGm5jA4eaHNOa5iUL/k899XZk2ylwu9S6tskPS/X2jOFnkvrZa+oFwn35OiBF6JausbDnkAmrbF8PUs0Qnfwz1Fg0j1WVhbeHqlr/MMN9Y4Lex3z8Nc7FWlc097EtzFI8e94JVIvHb1bmtYDxU8Ow4xxo3FnS6DkwporDpfso+AJqrutAQZ/RDsMoxtISi1UYN2xyW585F6MxU0=
  file:
    - "./dist/oracledb_exporter.linux-amd64"
    - "./dist/oracledb_exporter.darwin-amd64"
  on:
    repo: iamseth/oracledb_exporter

after_success:
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push iamseth/oracledb_exporter:${TRAVIS_TAG:-latest}

